[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"

[build]
providers = ["node"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npm run start"
